name: MyFirstPlugin
version: '${project.version}'
main: me.mischa.myfirstplugin.MyFirstPlugin
api-version: '1.20'
depend: [ProtocolLib]
commands:
  boom:
    description: big boom boom
  npc:
    description: no